### ISSUE TITLE
Busy.org German translation error in main navigation

### ISSUE THREAD

**Issue by Doki76** [busyorg/busy#1490]
#### Expected behavior
The navigation menu on the left side used to distinguish between trending and your feed.
Before it was translated to "Feed" for your feed from your followers and "Neuigkeiten" for the trending page. 
Finding a good translation here is difficult but I would suggest: 

Keep "Neue Posts" or "Neue Artikel" for the Feed from accounts you follow. And used "Trending" on the trending page also in German.  This would be in line with German translations of other big platforms.

#### Actual behavior
Now both menus are translated with "Neuigkeiten" As you can see in the screenshot. This requires improvement as it is difficult to use. "Neuigkeiten" also is not a word you would use stand alone as this describes neither the trending page correctly nor your news feed correctly.

#### How to reproduce
Logon to busy.org and switch languages to German.

#### Recording Of The Bug
![Busyorgmenue.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517653850/p678hpgpxjsmcpu92exl.jpg)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@drmake/busy-org-german-translation-error-in-main-navigation">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mktcode** [comment]
I suggest to simply translate "News" as "Trends" as it is the trendingpage.

Feed -> Neuigkeiten
News -> Trends

https://crowdin.com/translate/busy/22/en-de#1088

**Comment by Sekhmet** [comment]
Translations are handled on CrowdIn.

**Comment by dlepold** [comment]
Hello, even though I myself do speak some languages I'd love to promote steemit/busy etc. to friends who dont speak English, but i can't simply find German, Spanisch, French interfaces, also not on Busy.org - how can I access a Spanish Busy.org interface? Or is it not public? Is help needed? I do translations sometimes. I've seen that translations are hanled on CrowdIn - does it makes sense I do register there in order to help?
