### ISSUE TITLE
Removing bot advertisement - Suggestion

### ISSUE THREAD

**Issue by itharagaian** [busyorg/busy#1560]
#### Expected behavior
Remove or modify the text advertising the bot, the vote should be considered as a possible free bonus

#### Actual behavior

Seems to guarantee a vote if someone publish using busy, bringing complaints when vote does not occur

* Browser: All
* Operating system: All

**Comment by tonimese** [comment]
To this promise: 
![image](https://user-images.githubusercontent.com/20820467/36622546-6fb963ce-1906-11e8-9458-cdd9b5646377.png)
Maybe add thiis: "We are running an experiment with our upvoter bot"

**Comment by tonimese** [comment]
More and more people are complaining in Discord for not getting the busy vote:

Thunder_God - Today at 10:11 PM
":confused: Out of my last 6 posts, only 2 got the upvotes. That seems like something that should get looked into, if it consistently fails to upvote."

elevator09 - Yesterday at 12:12 AM
"I have not received the busy votes of the last days"

farhannaqvi7 - Last Tuesday at 9:27 PM
"Sir since 3 days i never get vote from busy.org"

Until a few days ago I supposed the bot does not vote if the Voting Power is lower than 16.6%. Then this message came:

crokkon - Last Wednesday at 10:58 AM
"... The bot votes at most every 2nd block / 6 seconds. A 0.06% vote every 6 seconds at 16.6% VP does not reduce the voting power and makes therefore a natural lower limit for the VP. With sometimes a bit more time between votes and a few votes > 0.06% this currently ends up at around 17-18% VP stable"

I don't know what is the cause for the increased number of skipped votes. I suppose the app can handle a limited number of votes per minute, or there could be other technical issues.

Anyway, the busy app is in beta testing and nothing is guaranteed. I guess if you find some ways to guarantee that won't be any issues, then the app would move out of beta.
