### ISSUE TITLE
<hr/> before an ![image] bug

### ISSUE THREAD

**Issue by tonimese** [busyorg/busy#1647]
#### Expected behavior

Add horizontal ruler right above an image.
![image](https://user-images.githubusercontent.com/20820467/37503177-8233fe86-28df-11e8-89c3-d048fb66a8e8.png)

#### Actual behavior

`<hr/>` (horizontal ruler) html tag right before a markdown image code, messes up with the rendering of the image

![image](https://user-images.githubusercontent.com/20820467/37503095-11867dd0-28df-11e8-8bc5-a9a32a1708ec.png)

#### How to reproduce
Write or edit a post with markdown like this:
![image](https://user-images.githubusercontent.com/20820467/37503051-cd6205a2-28de-11e8-8ee0-3ef98960167a.png)

#### Possible solution
add a blank line (cr) above the markdown image code
![image](https://user-images.githubusercontent.com/20820467/37503279-378c5d32-28e0-11e8-8b87-99ef15787966.png)

* Browser: Chromium
* Operating system: Ubuntu

Spotted by quochuy - Yesterday at 11:27 PM in Discord.
"Hi. there seem to be a bug when you add a separator tag `<hr/>` right before a markdown image code. This messes up with the rendering of the image once published, see my recent post for example: 
https://staging.busy.org/@quochuy/a-chrome-extension-to-help-with-scam-steemit-websites

**Comment by quochuy** [comment]
Adding a line after the HR works in the preview, but once the post is published, the layout is still messed up.

**Comment by hernandev** [comment]
fix:

```js
md.core.ruler.before('normalize', 'fix-hr', function (state) {
  state.src = state.src.replace('>\n![', '>\n\n![')
})
```

**Comment by hernandev** [comment]
BTW, the actual "solution" is to use Markdown on markdown editor :) 

```
line break below
---
``` 

line break below

---

line break above

**Comment by hernandev** [comment]
Ok, I gave up the lazy me and did the actual working version of that:

```js
const fixBreaks = function (md, options) {
  md.core.ruler.before('normalize', 'fix-breaks', function (state) {
    state.src = state.src.replace(/>\n/gi, '>\n\n')
  })
}
const parser = new MarkdownIt({ /* options here */ })
parser.use(fixBreaks)
```
export default plugin

**Comment by Sekhmet** [comment]
It's not an issue, but incorrect Markdown.
https://spec.commonmark.org/0.28/#html-blocks

**Comment by quochuy** [comment]
My posts still don't render properly, check the bottom of this:
https://busy-master-pr-1961.herokuapp.com/@quochuy/witness-update-2018-06-07-steem-communities-and-eos-witnessing

It does render properly on steemit.com:
https://steemit.com/witness-category/@quochuy/witness-update-2018-06-07-steem-communities-and-eos-witnessing

**Comment by bonustrack** [comment]
Happen aswell here: https://github.com/busyorg/busy/pull/1961#issuecomment-396640060

**Comment by hernandev** [comment]
@Sekhmet Almost all posts on Steem **are invalid** markdown, and since it's _valid_ on Steemit, users expect it to be valid elsewhere, sadly.

I shared that snippet but improved a little bit the process later, and created some other plugins for rendering.

I'll try to publish a common package we can colaborate on so we can have a _"default steem implementation"_ and hopefully no one has to hit the head against the wall parsing markdown.

**Comment by Sekhmet** [comment]
@hernandev I tried this snippet, it worked for simple cases, but quoted post still was messed up (because it's wrapped in `center` as well).

**Comment by Sekhmet** [comment]
Such package would be good idea, but I wouldn't expect Condenser to implement it.

**Comment by hernandev** [comment]
@Sekhmet I think just having a good ready to use package would be great to help two things: one: avoid reimplementing it everytime someone creates a steem related project, and two, have a good starting point on safe content parsing.

As for condenser, it's ok, and since from what I know they don't change things that much, it should be relatively simple to keep it up to date.
