### ISSUE TITLE
Hot Reloading fails on dev/local environment

### ISSUE THREAD

**Issue by jm90m** [busyorg/busy#1675]
#### Expected behavior
Hot Reloading to refresh page with most recent updates to files

#### Actual behavior
Memory allocation error, might possibly have to do with client-side web pack build

![screen shot 2018-03-23 at 9 39 34 am](https://user-images.githubusercontent.com/5067716/37832206-57d6324a-2e7e-11e8-9a99-1f226136772a.png)

#### How to reproduce
1. Run busy locally
2. Go to localhost:3000
3. Make changes in files
4. Go back to browser and wait for refresh or try to refresh page
5. Errors out and throws `CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` error

* Browser: Chrome
* Operating system: OSX

**Comment by Sekhmet** [comment]
If someone has a similar problem or it works fine for you please let me know your node version and OS.

For me it's working fine on:
node v8.11.1 on Ubuntu 16.04.

**Comment by th7nder** [comment]
Same thing happens to me, but it only happens when I do a mistake in code, like wrong function call etc.
Browser: Safari
Node: v8.9.4 NVM
OS: macOS High Sierra 10.13.4

`Security context: 0x1f60b1e25ee1 <JSObject>
    1: value [/Users/konrad/dev/src/busy/node_modules/less/lib/less/parser/parser.js:~1513] [pc=0x30266e7e7b5a](this=0x1f60ae1774b9 <Object map = 0x1f609d2c66c9>)
    2: rule [/Users/konrad/dev/src/busy/node_modules/less/lib/less/parser/parser.js:~1172] [pc=0x30266e7e6182](this=0x1f60ae1774b9 <Object map = 0x1f609d2c66c9>,tryAnonymous=0x1f605f502311 <undefined>)
    3: arguments adaptor frame: 0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/konrad/.nvm/versions/node/v8.9.4/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/konrad/.nvm/versions/node/v8.9.4/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/konrad/.nvm/versions/node/v8.9.4/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/konrad/.nvm/versions/node/v8.9.4/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/konrad/.nvm/versions/node/v8.9.4/bin/node]
 6: 0x30266d88463d`

**Comment by th7nder** [comment]
Changing antd to 2.3.11 helped me too. It fixed the issue and memory allocation problem does not happen anymore.

**Comment by jrawsthorne** [comment]
Same issue for me. Updating to the latest antd also helps.
Node v8.11.1 on Windows 10

**Comment by Sekhmet** [comment]
What version of antd are you using right now? `2.3.11` is older version than what we are using by default.
I made section in contributing guide about this problem:
https://docs.google.com/document/d/1tsR8ZOIF3Inf-KkZxZA3b0Q60Dct3Y0TmPhfuE5zbaA/edit#heading=h.encgzny60r5l
