### ISSUE TITLE
Mobile PopoverMenu media queries are off

### ISSUE THREAD

**Issue by Sekhmet** [busyorg/busy#1778]
#### Expected behavior

PopoverMenu should change to mobile view and center text at the same time.

#### Actual behavior

Text is centered before PopoverMenu switches to mobile view.
https://streamable.com/us9lw

#### How to reproduce

Open popover menu and slowly resize view port (~990px).

Reported by @jrawsthorne

**Comment by MeQuake** [comment]
The simplest way to fix this issue is just to change static inserted max-width value https://github.com/MeQuake/busy/commit/3696b9c5a9c229106934be6c4fd719ff54e77236#diff-eafdfd63b45cbbac79ef08565d083e4aR4 but it doesn't fix genesis of this issue.
I see we have file with variables for responsive design, but it seems that they are not enough https://github.com/MeQuake/busy/blob/master/src/client/styles/modules/variables.less

I think it should be reworked to catch all cases.
According to https://gist.github.com/seriema/e7605bbcdfc9eaf67ac3 and https://gist.github.com/bobbygrace/9e961e8982f42eb91b80#media-queries
I'm proposing something like this

```
@xs-and-up: ~"only screen";
@xs-only: ~"only screen and (max-width: 400px)";
@sm-and-up: ~"only screen and (min-width: 768px)";
@sm-only: ~"only screen and (min-width: 768px) and (max-width: 998px)";
@md-and-up: ~"only screen and (min-width: 998px)";
@md-only: ~"only screen and (min-width: 998px) and (max-width: 1200px)";
@lg-and-up: ~"only screen and (min-width: 1200px)";
@lg-only: @lg-and-up;

@print: ~"print";
@mobile: @xs-only; // Don't use this if you're using other sizes too, because Mobile First should be the default.
@tablet: @sm-only;
@desktop: @md-and-up;
```
It would be great to hear your opinions

**Comment by Sekhmet** [comment]
I think we should use few predefined variables with upper and lower boundaries (so `(min-width: 777px) and (max-width: 999px)`) and use this form everywhere. It's hard to keep everything consistent with overlapping breakpoints.
