### ISSUE TITLE
All posts including comments made by current user's account are showing as reblogged.

### ISSUE THREAD

**Issue by tobias-g1** [busyorg/busy#2193]
#### Expected behaviour

Only feed items that I have reblogged should be shown as reblogged, in the event, it was reblogged by someone else and now appears on my feed, it should state that it was reblogged by a particular author. 

#### Actual behavior

All items are showing a reblogged, even comments. 

#### How to reproduce

Go to your feed and scroll through, note that the reblogged item is shown as seen in the image below:

![image](https://user-images.githubusercontent.com/17148879/53360387-51c9c500-392d-11e9-94f3-bc03f26b8bdd.png)

an example of comments that I made can be seen here:

![image](https://user-images.githubusercontent.com/17148879/53360462-7f167300-392d-11e9-8325-81002d278293.png)

- Browser: Google Chrome (Version 71.0.3578.98 (Official Build) (64-bit))
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS Mojave Version 10.14.1 (18B75)

**Comment by economicstudio** [comment]
This doesn't happen on staging.busy.org Based on the communication with @Sekhmet and anyx, this and/or follower/ing info mismatch can be resolved with using hive.anyx.io instead of anyx.io. See https://steemit.com/utopian-io/@blockchainstudio/busy-user-page-loading-fail-page-not-found#@anyx/re-blockchainstudio-re-anyx-re-blockchainstudio-re-sekhmet-re-blockchainstudio-busy-user-page-loading-fail-page-not-found-20190226t195210453z

**Comment by Sekhmet** [comment]
hive.anyx.io isn't really compatible with API that Steemit is running. I've decided to stick to `anyx.io`, because using Steemit's API is just not worth it.

This issue has been fixed.
