### ISSUE TITLE
Image doesn't render in the post

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#828]
<img src="https://user-images.githubusercontent.com/16621517/31650163-60d716cc-b316-11e7-9e6a-7826a43f77ba.gif" height="280px"/>

<img src="https://user-images.githubusercontent.com/16621517/31650285-ef9648a6-b316-11e7-91d5-981a2d72d1dc.png" height="280px"/>

#### Expected behavior

The image should be rendered since it is showed in the post preview.

#### Actual behavior

The image renders in the post preview and in the image gallery but not in the post itself. This may be caused by the incorrect format of the image (see src and alt attributes).

#### How to reproduce

1. Go to `@dream.trip`
2. Find __The Big Buddha is Busy place__ `/photography/@dream.trip/the-big-buddha-is-busy-place`
3. See that image appears in the preview
4. Open the post
5. Image doesn't show up

* Browser: Chrome
* Operating system: Windows 10

**Comment by renderfiles** [comment]
This isn't a bug. If you goto https://steemd.com/photography/@dream.trip/the-big-buddha-is-busy-place and look at the original markdown text you can see he put ```![![20171002_172210.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1507061630/rdrydpyewrhpfhx0agn7.jpg)](url)``` This means it should be a link with a href of "url". The reason it has a preview picture is because the parser saw the link, and added the picture link to the links array, and into the image object, in the json_metadata.

**Comment by Kennybll** [comment]
This isn't a bug. If you goto https://steemd.com/photography/@dream.trip/the-big-buddha-is-busy-place and look at the original markdown text you can see he put ```![![20171002_172210.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1507061630/rdrydpyewrhpfhx0agn7.jpg)](url)``` This means it should be a link with a href of "url". The reason it has a preview picture is because the parser saw the link, and added the picture link to the links array, and into the image object, in the json_metadata.

**Comment by Sekhmet** [comment]
It's not a bug, but formatting error.
