### ISSUE TITLE
New busy not working in Internet Explorer

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#845]
<img src="https://user-images.githubusercontent.com/16621517/31737611-661e9690-b448-11e7-829e-0011a7438871.gif" height="280px"/>

#### Expected behavior

New busy should work in Internet Explorer.

#### Actual behavior

The page is blank. No content appears.

#### How to reproduce

1. Go to new busy in Internet Explorer

* Browser: Internet Explorer 11
* Operating system: Windows 10

**Comment by ryanbaer** [comment]
Wanted to comment - I started looking into this. The console has errors about `Object does not have property assign`.

This is somewhat expected since, in the [ES6 compatibility table](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;), Object.assign is not supported by IE11.

From what I've looked into so far, my guess is that it might have to do with us not loading babel-polyfill in webpack. But I haven't investigated enough yet to verify.

I'm currently working on another issue so if anyone else feels like taking this on in the meantime, hopefully these notes will help. If not, I'll come back to it.

**Comment by eastmaels** [comment]
I tried using the ff. in `webpack-dev-server.js`
```
  entry: {
    main: ['babel-polyfill', path.resolve(baseDir, './src/index.js')]
  },
```

it loaded in IE11, however the ff. error still occurs:
```
SCRIPT65535: Invalid calling object
```
