### ISSUE TITLE
header ...

### ISSUE THREAD

**Issue by karencarrens** [busyorg/busy#910]
#### Expected behavior

Right now, our thumbnail pic, display name, username, rank and reputation are left justified. Because it's left justified, it doesn't work with our current steemit cover picture. If you could simply center the info instead of left justify it, the Steemit cover picture will still work.

#### Actual behavior
![header 1](https://user-images.githubusercontent.com/32652555/32121701-5d619ed0-bb23-11e7-842e-779d87f946fb.JPG)

![header 2](https://user-images.githubusercontent.com/32652555/32121702-5d75f6be-bb23-11e7-84f7-0a26e38f75bf.JPG)

#### How to reproduce

* Browser: 
* Operating system:

**Comment by Sekhmet** [comment]
Hey,
this doesn't seem to be an issue. Busy has to meet expectations of a lot of people and still remain consistent and be itself. We sadly can't change the way user header looks to match your profile background, because this affects a lot of people and might break things for them.
As a side note, profile background is not well suited for more fancy images. There is a lot of different clients that people use and things look different on each of them. Additionally users use different devices and it might not look as good as on FullHD screen. I think that it should be kept simple.
