### ISSUE TITLE
User profile interesting people showed in wrong order

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#921]
When i'm on the homepage and click to my profile, the sidebar bar "Interesting people" will not show my top reblogged users. It seem to not be sorted. I need to refresh the page the see the real order.

This is not correct:
![image](https://user-images.githubusercontent.com/16245250/32136818-2300fdfe-bc3f-11e7-8afc-43272ad93099.png)

This is correct:
![image](https://user-images.githubusercontent.com/16245250/32136811-02b14b76-bc3f-11e7-8a96-7f5610044953.png)

**Comment by jm90m** [comment]
So the sidebar doesn't show people that you already follow, on my account, I tested this and mine are ordered by top reblogged users that I currently don't follow.

**Comment by ryanbaer** [comment]
@bonustrack I think this is in part because of a suggestion I made to @jm90m that, on your own page, it isn't much use to have Interesting People be full of people you already follow. So I don't think the ideal setup is to have it like the screenshot, with users you're already following, but rather to have like @jm90m said to be full of people you aren't yet following, as much as possible.

**Comment by jm90m** [comment]
Fixed in #1046. Please re-open if this issue still exists.
